version: "3.8"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: npm run dev

  fastapi:
    build:
      context: ./fastapi
    ports:
      - "8000:8000"
    env_file:
      - ./fastapi/.env
    volumes:
      - ./fastapi:/app
      - /app/venv
    command: >
      sh -c "python -m venv venv &&
             . venv/bin/activate &&
             pip install -r requirements.txt &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
